# command to run
# docker run \
#     --name mosdns \
#     -p 5454:53/udp \
#     -p 5454:53/tcp \
#     -v /etc/mosdns:/etc/mosdns
#     -d irinesistiana/mosdns

FROM irinesistiana/mosdns:v5.3.3
LABEL version="v5.3.3"
