# command to run
# docker run -d \
#     --cap-add=NET_ADMIN \
#     -p 1194:1194/udp \
#     -p 8833:8833 \
#     -e ADMIN_USERNAME=admin \
#     -e ADMIN_PASSWORD=admin \
#     -e OVPN_GATEWAY=true \
#     -v $(pwd)/data:/data \
#     yyxx/openvpn

FROM yyxx/openvpn:latest
LABEL version="latest"
