# command to run v2fly-core
# docker run \
#     --name v2ray \
#     -v /opt/v2ray/server.json:/etc/v2ray/config.json \
#     -p 12306:12306 \
#     -d --privileged \
#     v2fly/v2fly-core run -c /etc/v2ray/config.json

FROM v2fly/v2fly-core:v5.24.0
LABEL version="v5.24.0"
