name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [network-tools, system-tools]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.directory }}
          push: true
          tags: ${{ github.actor }}/${{ matrix.directory }}:latest
